### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by scarrazza** [N3PDF/mcnntunes_data#1]
@mlazzarin could you please add a README.md explaining the content of this repository?
We should cite this repo in the code docs, could you please take care of that?

**Comment by mlazzarin** [comment]
Ok.

**Comment by mlazzarin** [comment]
Pull request #2 should have completed the first point.
Now, if I understand correctly, I just need to cite this repo in the documentation of https://github.com/N3PDF/mcnntunes, right?

**Comment by scarrazza** [comment]
Yes

**Comment by mlazzarin** [comment]
Merge of pull request https://github.com/N3PDF/mcnntunes/pull/19 should have solved this issue, right?

**Comment by scarrazza** [comment]
Yes
